### ISSUE TITLE
선생님 도와주세요

### ISSUE THREAD

**Issue by dlarjsdn6** [2021-SMHRD-KDT-IoT-4/Mango#10]
기능 구현 질문

**Comment by nayeho** [comment]
1. Web의 값을 Arduino로 전송(response객체에 담아서 출력)
2. 스텝모터 2개 보드 1개 연결 후 구동가능한지 테스트 해봐야함
3. 스텝모터로 스프레이 누를 수 있는지 테스트 해봐야함
